import React, { useState } from 'react';
import axios from 'axios';
import { Line } from 'react-chartjs-2';
import { MapContainer, TileLayer, Marker, Popup, useMap } from 'react-leaflet';
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend } from 'chart.js';
import Navbar from './Navbar';
import Footer from './Footer';
import './CovidStats.css'; // Importar el archivo CSS
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import markerIcon from 'leaflet/dist/images/marker-icon.png';
import markerShadow from 'leaflet/dist/images/marker-shadow.png';
import CovidMap from './CovidMap'; // Asegúrate de importar CovidMap

// Registrar los componentes de Chart.js
ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend);

// Componente para mover el mapa
const SetViewOnClick = ({ coords }) => {
    const map = useMap();
    map.setView(coords, 4); // Ajusta el nivel de zoom aquí
    return null;
};

const countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia (Plurinational State of)",
    "Bonaire, Saint Eustatius and Saba",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "British Virgin Islands",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czechia",
    "Democratic People's Republic of Korea",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran (Islamic Republic of)",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia (Federated States of)",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands (Kingdom of the)",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "North Macedonia",
    "Northern Mariana Islands",
    "Norway",
    "occupied Palestinian territory, including east Jerusalem",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Republic of Korea",
    "Republic of Moldova",
    "Réunion",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Saint Barthélemy",
    "Saint Helena",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin (French part)",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten (Dutch part)",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Tajikistan",
    "Thailand",
    "United Kingdom of Great Britain and Northern Ireland",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Türkiye",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Republic of Tanzania",
    "United States of America",
    "United States Virgin Islands",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela (Bolivarian Republic of)",
    "Viet Nam",
    "Wallis and Futuna",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];

const customMarkerIcon = L.icon({
    iconUrl: markerIcon,
    shadowUrl: markerShadow,
    iconSize: [25, 41], // tamaño del icono
    iconAnchor: [12, 41], // punto de anclaje del icono (mitad inferior)
    popupAnchor: [1, -34], // punto de anclaje del popup en relación al icono
    shadowSize: [41, 41] // tamaño de la sombra
});

const CovidStats = () => {
    const [location, setLocation] = useState('');
    const [data, setData] = useState(null);
    const [error, setError] = useState('');
    const [coords, setCoords] = useState([20, 0]); // Coordenadas iniciales centradas

    const handleSearch = () => {
        if (!location) {
            setError("Please select a country.");
            return;
        }

        axios.get(`http://localhost:8000/covid-data?location=${location}`)
            .then(response => {
                console.log(response.data);
                setData(response.data);
                // Ajusta las coordenadas para centrar el mapa en el país encontrado
                const country = response.data.country;
                const countryCoords = getCountryCoordinates(country);
                setCoords(countryCoords);
            })
            .catch(error => {
                setError("Failed to fetch data. Please try again.");
                console.error("There was an error!", error);
            });
    };

    // Mapeo de nombres de países
    const country_name_mapping = {
        "Bangladesh": "Bangladesh",
        "Mayotte": "Mayotte",
        "Brunei Darussalam": "Brunei",
        "Luxembourg": "Luxembourg",
        "Sweden": "Sweden",
        "T�rkiye": "Turkey",
        "Syrian Arab Republic": "Syria",
        "Dominican Republic": "Dominican Republic",
        "Saint Helena": "Saint Helena",
        "Ireland": "Ireland",
        "Cambodia": "Cambodia",
        "Singapore": "Singapore",
        "San Marino": "San Marino",
        "Portugal": "Portugal",
        "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
        "United Kingdom of Great Britain y Northern Ireland": "United Kingdom",
        "Malta": "Malta",
        "Colombia": "Colombia",
        "Albania": "Albania",
        "Ukraine": "Ukraine",
        "Saudi Arabia": "Saudi Arabia",
        "Sao Tome and Principe": "Sao Tome and Principe",
        "Sao Tome y Principe": "Sao Tome and Principe",
        "Latvia": "Latvia",
        "Algeria": "Algeria",
        "Slovakia": "Slovakia",
        "Maldives": "Maldives",
        "Israel": "Israel",
        "Malaysia": "Malaysia",
        "Kenya": "Kenya",
        "Zambia": "Zambia",
        "Kuwait": "Kuwait",
        "Liberia": "Liberia",
        "Bosnia and Herzegovina": "Bosnia and Herzegovina",
        "Bosnia y Herzegovina": "Bosnia and Herzegovina",
        "Benin": "Benin",
        "Cyprus": "Cyprus",
        "Nigeria": "Nigeria",
        "Tajikistan": "Tajikistan",
        "Guam": "Guam",
        "China": "China",
        "Sint Maarten (Dutch part)": "Sint Maarten",
        "New Caledonia": "New Caledonia",
        "Armenia": "Armenia",
        "Qatar": "Qatar",
        "Gabon": "Gabon",
        "Netherlands (Kingdom of the)": "Netherlands",
        "Martinique": "Martinique",
        "Australia": "Australia",
        "Dominica": "Dominica",
        "Serbia": "Serbia",
        "Saint Barth�lemy": "Saint Barthelemy",
        "British Virgin Islands": "British Virgin Islands",
        "Islas Vírgenes Británicas": "British Virgin Islands",
        "Libya": "Libya",
        "Vanuatu": "Vanuatu",
        "Wallis and Futuna": "Wallis and Futuna",
        "Wallis y Futuna": "Wallis and Futuna",
        "Congo": "Congo",
        "United Arab Emirates": "United Arab Emirates",
        "Emiratos Árabes Unidos": "United Arab Emirates",
        "Georgia": "Georgia",
        "Belgium": "Belgium",
        "Monaco": "Monaco",
        "Guernsey": "Guernsey",
        "occupied Palestinian territory, including east Jerusalem": "Palestine",
        "Territorio palestino ocupado, incluida Jerusalén oriental": "Palestine",
        "Democratic Republic of the Congo": "Democratic Republic of the Congo",
        "República Democrática del Congo": "Democratic Republic of the Congo",
        "Cura�ao": "Curacao",
        "Curazao": "Curacao",
        "Solomon Islands": "Solomon Islands",
        "Islas Salomón": "Solomon Islands",
        "Montserrat": "Montserrat",
        "Thailand": "Thailand",
        "Tailandia": "Thailand",
        "El Salvador": "El Salvador",
        "Democratic People's Republic of Korea": "North Korea",
        "República Popular Democrática de Corea": "North Korea",
        "Uruguay": "Uruguay",
        "Kosovo (in accordance with UN Security Council resolution 1244 (1999))": "Kosovo",
        "Kosovo (de acuerdo con la resolución 1244 (1999) del Consejo de Seguridad de la ONU)": "Kosovo",
        "Germany": "Germany",
        "Alemania": "Germany",
        "Eritrea": "Eritrea",
        "Canada": "Canada",
        "Canadá": "Canada",
        "Barbados": "Barbados",
        "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
        "San Vicente y las Granadinas": "Saint Vincent and the Grenadines",
        "Namibia": "Namibia",
        "Marshall Islands": "Marshall Islands",
        "Islas Marshall": "Marshall Islands",
        "Cook Islands": "Cook Islands",
        "Islas Cook": "Cook Islands",
        "Slovenia": "Slovenia",
        "Azerbaijan": "Azerbaijan",
        "Azerbaiyán": "Azerbaijan",
        "Greece": "Greece",
        "Grecia": "Greece",
        "Egypt": "Egypt",
        "Egipto": "Egypt",
        "Afghanistan": "Afghanistan",
        "Afganistán": "Afghanistan",
        "Chad": "Chad",
        "Timor-Leste": "Timor-Leste",
        "Timor Oriental": "Timor-Leste",
        "Saint Kitts and Nevis": "Saint Kitts and Nevis",
        "San Cristóbal y Nieves": "Saint Kitts and Nevis",
        "Chile": "Chile",
        "Suriname": "Suriname",
        "Surinam": "Suriname",
        "South Africa": "South Africa",
        "Sudáfrica": "South Africa",
        "Peru": "Peru",
        "Perú": "Peru",
        "Isle of Man": "Isle of Man",
        "Kazakhstan": "Kazakhstan",
        "Kazajistán": "Kazakhstan",
        "Japan": "Japan",
        "Japón": "Japan",
        "Jamaica": "Jamaica",
        "Pitcairn": "Pitcairn Islands",
        "Iraq": "Iraq",
        "Irak": "Iraq",
        "New Zealand": "New Zealand",
        "Nueva Zelanda": "New Zealand",
        "Ecuador": "Ecuador",
        "Norway": "Norway",
        "Noruega": "Norway",
        "Pakistan": "Pakistan",
        "Pakistán": "Pakistan",
        "Brazil": "Brazil",
        "Brasil": "Brazil",
        "Guatemala": "Guatemala",
        "R�union": "Reunion",
        "Reunión": "Reunion",
        "Ethiopia": "Ethiopia",
        "Etiopía": "Ethiopia",
        "Saint Martin (French part)": "Saint Martin",
        "San Martín (parte francesa)": "Saint Martin",
        "Panama": "Panama",
        "Panamá": "Panama",
        "Yemen": "Yemen",
        "South Sudan": "South Sudan",
        "Sudán del Sur": "South Sudan",
        "Tunisia": "Tunisia",
        "Túnez": "Tunisia",
        "Sudan": "Sudan",
        "Sudán": "Sudan",
        "Mali": "Mali",
        "North Macedonia": "North Macedonia",
        "Macedonia del Norte": "North Macedonia",
        "Morocco": "Morocco",
        "Marruecos": "Morocco",
        "International conveyance (Diamond Princess)": "Diamond Princess",
        "Myanmar": "Myanmar",
        "Mexico": "Mexico",
        "México": "Mexico",
        "Guyana": "Guyana",
        "Poland": "Poland",
        "Polonia": "Poland",
        "Lebanon": "Lebanon",
        "Líbano": "Lebanon",
        "French Guiana": "French Guiana",
        "Guayana Francesa": "French Guiana",
        "Turks and Caicos Islands": "Turks and Caicos Islands",
        "Islas Turcas y Caicos": "Turks and Caicos Islands",
        "Czechia": "Czech Republic",
        "Chequia": "Czech Republic",
        "Indonesia": "Indonesia",
        "Iran (Islamic Republic of)": "Iran",
        "Irán (República Islámica del)": "Iran",
        "Kiribati": "Kiribati",
        "Cameroon": "Cameroon",
        "Camerún": "Cameroon",
        "Viet Nam": "Vietnam",
        "Vietnam": "Vietnam",
        "Uganda": "Uganda",
        "Montenegro": "Montenegro",
        "Jordan": "Jordan",
        "Jordania": "Jordan",
        "International commercial vessel": "International Vessel",
        "Papua New Guinea": "Papua New Guinea",
        "Papúa Nueva Guinea": "Papua New Guinea",
        "Sri Lanka": "Sri Lanka",
        "American Samoa": "American Samoa",
        "Samoa Americana": "American Samoa",
        "Uzbekistan": "Uzbekistan",
        "Uzbekistán": "Uzbekistan",
        "Finland": "Finland",
        "Finlandia": "Finland",
        "Grenada": "Grenada",
        "Cayman Islands": "Cayman Islands",
        "Islas Caimán": "Cayman Islands",
        "Cuba": "Cuba",
        "Tokelau": "Tokelau",
        "Kyrgyzstan": "Kyrgyzstan",
        "Kirguistán": "Kyrgyzstan",
        "France": "France",
        "Francia": "France",
        "Djibouti": "Djibouti",
        "Yibuti": "Djibouti",
        "Nauru": "Nauru",
        "Senegal": "Senegal",
        "Ghana": "Ghana",
        "Iceland": "Iceland",
        "Islandia": "Iceland",
        "Madagascar": "Madagascar",
        "Sierra Leone": "Sierra Leone",
        "Filipinas": "Philippines",
        "Philippines": "Philippines",
        "Tuvalu": "Tuvalu",
        "Cabo Verde": "Cape Verde",
        "Cape Verde": "Cape Verde",
        "Guinea": "Guinea",
        "Rwanda": "Rwanda",
        "Zimbabwe": "Zimbabwe",
        "Lao People's Democratic Republic": "Laos",
        "Laos": "Laos",
        "Comoros": "Comoros",
        "Comoras": "Comoros",
        "Saint Lucia": "Saint Lucia",
        "Santa Lucía": "Saint Lucia",
        "Belarus": "Belarus",
        "Lesotho": "Lesotho",
        "Paraguay": "Paraguay",
        "Mauritius": "Mauritius",
        "Mauricio": "Mauritius",
        "Angola": "Angola",
        "Bahrain": "Bahrain",
        "Baréin": "Bahrain",
        "Spain": "Spain",
        "España": "Spain",
        "Saint Pierre and Miquelon": "Saint Pierre and Miquelon",
        "San Pedro y Miquelón": "Saint Pierre and Miquelon",
        "Malawi": "Malawi",
        "Burundi": "Burundi",
        "Republic of Korea": "South Korea",
        "Corea del Sur": "South Korea",
        "Bhutan": "Bhutan",
        "Bután": "Bhutan",
        "Togo": "Togo",
        "Niue": "Niue",
        "International conveyance (Kiribati)": "International Vessel",
        "Burkina Faso": "Burkina Faso",
        "Faroe Islands": "Faroe Islands",
        "Islas Feroe": "Faroe Islands",
        "Italy": "Italy",
        "Italia": "Italy",
        "Oman": "Oman",
        "Omán": "Oman",
        "Venezuela (Bolivarian Republic of)": "Venezuela",
        "Venezuela (República Bolivariana de)": "Venezuela",
        "Micronesia (Federated States of)": "Micronesia",
        "Eswatini": "Eswatini",
        "Fiji": "Fiji",
        "Palau": "Palau",
        "Holy See": "Vatican City",
        "Vaticano": "Vatican City",
        "International conveyance (Vanuatu)": "International Vessel",
        "Anguilla": "Anguilla",
        "C�te d'Ivoire": "Ivory Coast",
        "Costa de Marfil": "Ivory Coast",
        "Bermuda": "Bermuda",
        "United Republic of Tanzania": "Tanzania",
        "República Unida de Tanzania": "Tanzania",
        "Argentina": "Argentina",
        "Liechtenstein": "Liechtenstein",
        "Bahamas": "Bahamas",
        "Puerto Rico": "Puerto Rico",
        "India": "India",
        "Bonaire, Saint Eustatius and Saba": "Caribbean Netherlands",
        "Bonaire, San Eustaquio y Saba": "Caribbean Netherlands",
        "French Polynesia": "French Polynesia",
        "Polinesia Francesa": "French Polynesia",
        "Gambia": "Gambia",
        "Estonia": "Estonia",
        "Central African Republic": "Central African Republic",
        "República Centroafricana": "Central African Republic",
        "Guadeloupe": "Guadeloupe",
        "Denmark": "Denmark",
        "Dinamarca": "Denmark",
        "Trinidad and Tobago": "Trinidad and Tobago",
        "Trinidad y Tobago": "Trinidad and Tobago",
        "Mongolia": "Mongolia",
        "United States of America": "United States",
        "Estados Unidos": "United States",
        "Mauritania": "Mauritania",
        "Mozambique": "Mozambique",
        "Switzerland": "Switzerland",
        "Suiza": "Switzerland",
        "Seychelles": "Seychelles",
        "Northern Mariana Islands": "Northern Mariana Islands",
        "Hungary": "Hungary",
        "Hungría": "Hungary",
        "Honduras": "Honduras",
        "Belize": "Belize",
        "Botswana": "Botswana",
        "Russian Federation": "Russia",
        "Federación de Rusia": "Russia",
        "Romania": "Romania",
        "Rumania": "Romania",
        "Austria": "Austria",
        "International conveyance (American Samoa)": "International Vessel",
        "Guinea-Bissau": "Guinea-Bissau",
        "Falkland Islands (Malvinas)": "Falkland Islands",
        "Islas Malvinas": "Falkland Islands",
        "Niger": "Niger",
        "International conveyance (Solomon Islands)": "International Vessel",
        "Lithuania": "Lithuania",
        "Lituania": "Lithuania",
        "Bulgaria": "Bulgaria",
        "Turkmenistan": "Turkmenistan",
        "Turkmenistán": "Turkmenistan",
        "Croatia": "Croatia",
        "Croacia": "Croatia",
        "Aruba": "Aruba",
        "Nicaragua": "Nicaragua",
        "Tonga": "Tonga",
        "Nepal": "Nepal",
        "United States Virgin Islands": "United States Virgin Islands",
        "Islas Vírgenes de los Estados Unidos": "United States Virgin Islands",
        "Bolivia (Plurinational State of)": "Bolivia",
        "Bolivia (Estado Plurinacional de)": "Bolivia",
        "Greenland": "Greenland",
        "Groenlandia": "Greenland",
        "Costa Rica": "Costa Rica",
        "Republic of Moldova": "Moldova",
        "República de Moldova": "Moldova",
        "Jersey": "Jersey",
        "Haiti": "Haiti",
        "Haití": "Haiti",
        "Gibraltar": "Gibraltar",
        "Samoa": "Samoa",
        "Equatorial Guinea": "Equatorial Guinea",
        "Guinea Ecuatorial": "Equatorial Guinea",
        "Antigua and Barbuda": "Antigua and Barbuda",
        "Antigua y Barbuda": "Antigua and Barbuda",
        "Somalia": "Somalia",
        "Andorra": "Andorra",
    };

    // Función para obtener las coordenadas del país
    const getCountryCoordinates = (country) => {
        const mappedCountryName = country_name_mapping[country] || country;
        const countryCoordinates = {
            'Afghanistan': [33.0, 65.0],
            'Albania': [41.3333, 19.8167],
            'Algeria': [28.0339, 1.6596],
            'American Samoa': [-14.2700, -170.1322],
            'Andorra': [42.5462, 1.6016],
            'Angola': [-11.2027, 17.8739],
            'Anguilla': [18.2206, -63.0686],
            'Antigua and Barbuda': [17.0608, -61.7964],
            'Argentina': [-38.4161, -63.6167],
            'Armenia': [40.0691, 45.0382],
            'Aruba': [12.5211, -69.9683],
            'Australia': [-25.2744, 133.7751],
            'Austria': [47.5162, 14.5501],
            'Azerbaijan': [40.1431, 47.5769],
            'Bahamas': [25.0343, -77.3963],
            'Bahrain': [25.9304, 50.6378],
            'Bangladesh': [23.6850, 90.3563],
            'Barbados': [13.1939, -59.5432],
            'Belarus': [53.7098, 27.9534],
            'Belgium': [50.5039, 4.4699],
            'Belize': [17.1899, -88.4976],
            'Benin': [9.3077, 2.3158],
            'Bermuda': [32.3078, -64.7505],
            'Bhutan': [27.5142, 90.4336],
            'Bolivia': [-16.2902, -63.5887],
            'Bonaire, Sint Eustatius and Saba': [12.2019, -68.2624],
            'Bosnia and Herzegovina': [43.9159, 17.6791],
            'Botswana': [-22.3285, 24.6849],
            'Brazil': [-14.2350, -51.9253],
            'British Virgin Islands': [18.4207, -64.6399],
            'Brunei Darussalam': [4.5353, 114.7277],
            'Bulgaria': [42.7339, 25.4858],
            'Burkina Faso': [12.2383, -1.5616],
            'Burundi': [-3.3731, 29.9189],
            'Cabo Verde': [16.5388, -23.0418],
            'Cambodia': [12.5657, 104.9910],
            'Cameroon': [7.3697, 12.3547],
            'Canada': [56.1304, -106.3468],
            'Cayman Islands': [19.3133, -81.2546],
            'Central African Republic': [6.6111, 20.9394],
            'Chad': [15.4542, 18.7322],
            'Chile': [-35.6751, -71.5430],
            'China': [35.8617, 104.1954],
            'Colombia': [4.5709, -74.2973],
            'Comoros': [-11.6455, 43.3333],
            'Congo': [-0.2280, 15.8277],
            'Cook Islands': [-21.2367, -159.7777],
            'Costa Rica': [9.7489, -83.7534],
            'Côte d\'Ivoire': [7.5400, -5.5471],
            'Croatia': [45.1000, 15.2000],
            'Cuba': [21.5218, -77.7812],
            'Curacao': [12.1696, -68.9900],
            'Cyprus': [35.1264, 33.4299],
            'Czechia': [49.8175, 15.4730],
            'North Korea': [40.3399, 127.5101],
            'Democratic Republic of the Congo': [-4.0383, 21.7587],
            'Denmark': [56.2639, 9.5018],
            'Djibouti': [11.8251, 42.5903],
            'Dominica': [15.4140, -61.3709],
            'Dominican Republic': [18.7357, -70.1627],
            'Ecuador': [-1.8312, -78.1834],
            'Egypt': [26.8206, 30.8025],
            'El Salvador': [13.7942, -88.8965],
            'Equatorial Guinea': [1.6508, 10.2679],
            'Eritrea': [15.1794, 39.7823],
            'Estonia': [58.5953, 25.0136],
            'Eswatini': [-26.5225, 31.4659],
            'Ethiopia': [9.1450, 40.4897],
            'Falkland Islands': [-51.7963, -59.5236],
            'Faroe Islands': [61.8926, -6.9118],
            'Fiji': [-17.7134, 178.0650],
            'Finland': [61.9241, 25.7482],
            'France': [46.6034, 1.8883],
            'French Guiana': [3.9339, -53.1258],
            'French Polynesia': [-17.6797, -149.4068],
            'Gabon': [-0.8037, 11.6094],
            'Gambia': [13.4432, -15.3101],
            'Georgia': [42.3154, 43.3569],
            'Germany': [51.0, 9.0],
            'Ghana': [7.9465, -1.0232],
            'Gibraltar': [36.1408, -5.3536],
            'Greece': [39.0742, 21.8243],
            'Greenland': [71.7069, -42.6043],
            'Grenada': [12.1165, -61.6790],
            'Guadeloupe': [16.2650, -61.5510],
            'Guam': [13.4443, 144.7937],
            'Guatemala': [15.7835, -90.2308],
            'Guernsey': [49.4657, -2.5853],
            'Guinea': [9.9456, -9.6966],
            'Guinea-Bissau': [11.8037, -15.1804],
            'Guyana': [4.8604, -58.9302],
            'Haiti': [18.9712, -72.2852],
            'Holy See': [41.9029, 12.4534],
            'Honduras': [15.2000, -86.2419],
            'Hungary': [47.1625, 19.5033],
            'Iceland': [64.9631, -19.0208],
            'India': [20.5937, 78.9629],
            'Indonesia': [-0.7893, 113.9213],
            'Iran': [32.4279, 53.6880],
            'Iraq': [33.2232, 43.6793],
            'Ireland': [53.4129, -8.2439],
            'Isle of Man': [54.2361, -4.5481],
            'Israel': [31.0461, 34.8516],
            'Italy': [41.8719, 12.5674],
            'Jamaica': [18.1096, -77.2975],
            'Japan': [36.2048, 138.2529],
            'Jersey': [49.2144, -2.1312],
            'Jordan': [30.5852, 36.2384],
            'Kazakhstan': [48.0196, 66.9237],
            'Kenya': [-1.2864, 36.8172],
            'Kiribati': [1.8709, -157.3624],
            'Kosovo': [42.6026, 20.9030],
            'Kuwait': [29.3117, 47.4818],
            'Kyrgyzstan': [41.2044, 74.7661],
            'Laos': [19.8563, 102.4955],
            'Latvia':[56.8796, 24.6032],
            'Lebanon': [33.8547, 35.8623],
            'Lesotho': [-29.6094, 28.2336],
            'Liberia': [6.4281, -9.4295],
            'Libya': [26.3351, 17.2284],
            'Liechtenstein': [47.1660, 9.5554],
            'Lithuania': [55.1694, 23.8813],
            'Luxembourg': [49.8153, 6.1296],
            'Madagascar': [-18.7669, 46.8691],
            'Malawi': [-13.2543, 34.3015],
            'Malaysia': [4.2105, 101.9758],
            'Maldives': [3.2028, 73.2207],
            'Mali': [17.5707, -3.9962],
            'Malta': [35.9375, 14.3754],
            'Marshall Islands': [7.1147, 171.2064],
            'Mauritania': [21.0079, -10.9408],
            'Mauritius': [-20.3484, 57.5522],
            'Mexico': [23.6345, -102.5528],
            'Micronesia': [7.4250, 150.5508],
            'Moldova': [47.4116, 28.3699],
            'Monaco': [43.7333, 7.4167],
            'Mongolia': [46.8625, 103.8467],
            'Montenegro': [42.7087, 19.3744],
            'Montserrat': [16.7500, -62.2000],
            'Morocco': [31.7917, -7.0926],
            'Mozambique': [-18.6657, 35.5296],
            'Myanmar': [21.9139, 95.9560],
            'Namibia': [-22.5597, 17.0833],
            'Nauru': [-0.5228, 166.9315],
            'Nepal': [28.3949, 84.1240],
            'Netherlands': [52.3676, 4.9041],
            'New Caledonia': [-20.9043, 165.6180],
            'New Zealand': [-40.9006, 174.8860],
            'Nicaragua': [12.8654, -85.2072],
            'Niger': [17.6078, 8.0817],
            'Nigeria': [9.0820, 8.6753],
            'Niue': [-19.0544, -169.8672],
            'Norfolk Island': [-29.0408, 167.9500],
            'North Macedonia': [41.6086, 21.7453],
            'Northern Mariana Islands': [15.0979, 145.6739],
            'Norway': [60.4720, 8.4689],
            'Oman': [21.5126, 55.9233],
            'Pakistan': [30.3753, 69.3451],
            'Palau': [7.5149, 134.5825],
            'Palestine': [31.9474, 35.3026],
            'Panama': [8.9824, -79.5200],
            'Papua New Guinea': [-6.3149, 143.9555],
            'Paraguay': [-23.4420, -58.4438],
            'Peru': [-9.1900, -75.0152],
            'Philippines': [12.8797, 121.7740],
            'Pitcairn': [-25.0660, -130.1000],
            'Poland': [51.9194, 19.1451],
            'Portugal': [39.3999, -8.2245],
            'Puerto Rico': [18.2208, -66.5901],
            'Qatar': [25.2769, 51.5200],
            'Réunion': [-21.1151, 55.5364],
            'Romania': [45.9432, 24.9668],
            'Russian Federation': [61.5240, 105.3188],
            'Rwanda': [-1.9403, 29.8739],
            'Saint Barthelemy': [17.9000, -62.8500],
            'Saint Helena': [-15.9650, -5.7050],
            'Saint Kitts and Nevis': [17.3578, -62.7820],
            'Saint Lucia': [13.9094, -60.9789],
            'Saint Martin': [18.0708, -63.0501],
            'Saint Pierre and Miquelon': [46.8251, -56.3232],
            'Saint Vincent and the Grenadines': [12.9843, -61.2870],
            'Samoa': [-13.7590, -172.1046],
            'San Marino': [43.9333, 12.4500],
            'Sao Tome and Principe': [0.1864, 6.6131],
            'Saudi Arabia': [23.8859, 45.0792],
            'Senegal': [14.6928, -14.0068],
            'Serbia': [44.0165, 21.0059],
            'Seychelles': [-4.6796, 55.4915],
            'Sierra Leone': [8.4606, -11.7799],
            'Singapore': [1.3521, 103.8198],
            'Sint Maarten': [18.0420, -63.0628],
            'Slovakia': [48.6690, 19.6990],
            'Slovenia': [46.1512, 14.9955],
            'Solomon Islands': [-9.4295, 160.0000],
            'Somalia': [5.1521, 46.1996],
            'South Africa': [-30.5595, 22.9375],
            'South Sudan': [6.8769, 31.3069],
            'Spain': [40.4637, -3.7492],
            'Sri Lanka': [7.8731, 80.7718],
            'Sudan': [12.8628, 30.2176],
            'Suriname': [3.9193, -56.0278],
            'Svalbard and Jan Mayen': [77.5591, 23.9498],
            'Sweden': [60.1282, 18.6435],
            'Switzerland': [46.8182, 8.2275],
            'Syria': [34.8021, 38.9968],
            'Taiwan': [23.6978, 120.9605],
            'Tajikistan': [38.8610, 71.2761],
            'Tanzania': [-6.3690, 34.8888],
            'Thailand': [15.8700, 100.9925],
            'Timor-Leste': [-8.8742, 125.7275],
            'Togo': [8.6195, 0.8248],
            'Tokelau': [-9.2000, -171.8000],
            'Tonga': [-21.1789, -175.1982],
            'Trinidad and Tobago': [10.6918, -61.2225],
            'Tunisia': [33.8869, 9.5375],
            'Turkey': [38.9637, 35.2433],
            'Turkmenistan': [38.9697, 59.5563],
            'Tuvalu': [-7.1095, 179.1940],
            'Uganda': [1.3733, 32.2903],
            'Ukraine': [48.3794, 31.1656],
            'United Arab Emirates': [23.4241, 53.8478],
            'United Kingdom': [55.3781, -3.4360],
            'United States': [37.0902, -95.7129],
            'Uruguay': [-32.5228, -55.7654],
            'Uzbekistan': [41.3775, 64.5850],
            'Vanuatu': [-15.3767, 166.9592],
            'Venezuela': [6.4238, -66.5897],
            'Viet Nam': [14.0583, 108.2772],
            'Western Sahara': [24.2155, -12.8858],
            'Yemen': [15.5524, 48.5164],
            'Zambia': [-13.1339, 27.8493],
            'Zimbabwe': [-19.0154, 29.1549]
        };
        
        if (countryCoordinates[mappedCountryName]) {
            return countryCoordinates[mappedCountryName];
        } else {
            console.error(`Coordenadas no encontradas para el país: ${country}. Mostrando coordenadas por defecto.`);
            return [20, 0]; // Coordenadas por defecto
        }
    };

    // Configuración de datos para el gráfico
    const chartData = {
        labels: ['Total Cases', 'New Cases', 'Total Deaths'],
        datasets: [
            {
                label: 'COVID-19 Stats',
                data: [data?.cumulative_cases, data?.new_cases, data?.cumulative_deaths],
                backgroundColor: ['rgba(75, 192, 192, 0.6)'],
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 2,
                fill: false,
            },
        ],
    };

    const chartOptions = {
        responsive: true,
        plugins: {
            legend: {
                display: true,
            },
            title: {
                display: true,
                text: 'COVID-19 Statistics',
            },
        },
    };

    return (
        <div>
            <Navbar />
            <div className="covid-stats-container">
                <h2>Find your country</h2>
                <div className="search-container">
                    <select
                        className="search-input"
                        value={location}
                        onChange={e => setLocation(e.target.value)}
                    >
                        <option value="">Select a country</option>
                        {countries.map((country, index) => (
                            <option key={index} value={country}>
                                {country}
                            </option>
                        ))}
                    </select>
                    <button className="search-button" onClick={handleSearch}>Search</button>
                </div>
                {error && <p className="error-message">{error}</p>}
                {data && (
                    <div>
                        <table className="stats-table">
                            <thead>
                                <tr>
                                    <th>Country</th>
                                    <th>Total Cases</th>
                                    <th>New Cases (Last 7 Days)</th>
                                    <th>Total Deaths</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>{data.country}</td>
                                    <td>{data.cumulative_cases}</td>
                                    <td>{data.new_cases}</td>
                                    <td>{data.cumulative_deaths}</td>
                                </tr>
                            </tbody>
                        </table>
                        <Line data={chartData} options={chartOptions} />
                    </div>
                )}
            </div>
            <div className="map-container">
                <h3>Map Visualization</h3>
                <MapContainer className="leaflet-container" center={coords} zoom={2}>
                    <TileLayer
                        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
                    />
                    {data && (
                        <>
                            <SetViewOnClick coords={coords} />
                            <Marker position={coords} icon={customMarkerIcon}>
                                <Popup>
                                    {data.country}
                                </Popup>
                            </Marker>
                        </>
                    )}
                </MapContainer>
            </div>
            <Footer />
        </div>
    );
};

export default CovidStats;